
        <h2><i class="fa fa-lock"></i> Se connecter avec un compte utilisateur</h2>

<form class="generic-form" action="<?=$requestUrl?>/user/login" method="POST">

<div class="main">
      <a  style="margin-left: 90%"href="<?= $requestUrl ?>/register"><button class="rigth button button-primary" type="button">Inscription</button></a>
  <fieldset>
    <legend>Informations d'authentification</legend>

    <label for="email">E-mail :</label>
    <input id="email" type="text" name="email" data-required="" data-name="E-mail" value="">

    <label for="password">Mot de passe :</label>
    <input id="password" type="password" name="password" data-required="" data-name="Mot de passe">

  </fieldset>


  <input class="button button-primary" type="submit" value="Connexion">
  <a class="button button-cancel small" href="<?=$requestUrl?>">Annuler</a>

</div>

</form>
