<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Dream of mangas</title>
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.5.0/css/all.css" integrity="sha384-B4dIYHKNBt8Bc12p+WXckhzcICo0wtJAoU8YZTY5qE0Id1GSseTk6S+L3BlXeVIU" crossorigin="anonymous">
    <link rel="stylesheet" href="<?= $wwwUrl ?>/css/style.css">

    <!-- Librairie jQuery -->
    <script src="http://code.jquery.com/jquery-2.1.0.min.js"></script>

    <!-- JavaScript de l'application -->
    <script src="<?= $wwwUrl ?>/js/utilities.js"></script>
</head>
<body>
  <header>
    <a href="<?= $requestUrl ?>"><h1>Adri*j</h1></a>
    <p>Forum de discution</p>
<nav>
  <ul>

    <a href="<?= $requestUrl ?>"><li>Accueil</li></a>

    <a href="<?= $requestUrl ?>/contact"><li>Nous contacter</li></a>
  </ul>
</nav>
  </header>

<main>
    <!-- Affichage du template lié à la vue -->
    <?php include $this->viewData['template'] ?>
</main>

<!-- Pied de page commun -->
<footer>
  <p> Merci de votre visite  hesité pas a partager à vos amis</p>

  <em>Adrij fondation  © 2018</em>
</footer>


</body>
</html>
