<?php if(array_key_exists('user', $_SESSION) == false) {
  $http = new Http();
  $http->redirectTo('/user/login');}
  else {?>
<div class="main">
  <?php foreach ($com as $key => $value): ?>

    <p style='color: black;'> <em>Commentaire écris par <?=$value['FirstName']?> <?=$value['LastName']?> :</em></p>
    <p><?=$value['avis']?>

<?php if ($value['user_Id'] == $_SESSION['user']['Id'] ) {?>
      <a style="color: #5ee3a7;" href="<?=$requestUrl?>/delete?id=<?=$value['Id']?>"><i class="fas fa-trash-alt poubelle"></i>
      </a>

<?php } ?>
    </p>


    <hr>
  <?php endforeach; ?>

    <a class="button button-cancel" href="<?=$requestUrl?>/avis?id=<?=$_GET['id']?>">Retour</a>

</div>
<?php } ?>
