<div class="main">
  <h2><i class="fa fa-user"></i> Création d'un compte</h2>

  <form class="generic-form" action="<?= $requestUrl ?>/login" method="POST">

    </aside>

    <fieldset>
      <legend><i class="fa fa-book"></i> Identité</legend>

      <label for="lastName">Nom :</label>
      <input id="lastName" type="text" name="lastName" data-required="" data-name="Nom" value="">
      <!--input id="lastName" type="text" name="lastName" value=""-->

      <label for="firstName">Prénom :</label>
      <input id="firstName" type="text" name="firstName" data-required="" data-name="Prénom" value="">

    </fieldset>
    <fieldset>
      <legend><i class="fa fa-lock"></i> Informations d'authentification</legend>

      <label for="email">E-mail :</label>
      <input id="email" type="text" name="email" data-required="" data-name="E-mail" value="">

      <label for="password">Mot de passe :</label>
      <input id="password" type="password" name="password" data-required="" data-name="Mot de passe" data-length="8">

    </fieldset>


    <input class="button button-primary" type="submit" value="Créer le compte">
    <a class="<?= $requestUrl ?>"><button class="button button-cancel small" type="button" name="button">Annuler</button></a>

  </form>

</div>
