<?php if(array_key_exists('user', $_SESSION) && $_SESSION['user']['Id'] == 1) {
?>
<div class="main">
  <h2><i class="fa fa-user"></i>Admin page</h2>

  <form class="generic-form" action="<?= $requestUrl ?>/admin" method="POST">


    <fieldset>
      mangas<legend><i class="fa fa-book"></i> </legend>

      <label for="nom">Nom du mangas :</label>
      <input id="nom" type="text" name="nom" value="">
      <!--input id="lastName" type="text" name="lastName" value=""-->

      <label for="resume">resume :</label>
      <input id="resume" type="text" name="resume" value="">

      <label for="date">date :</label>
      <input id="date" type="text" name="date" value="">

      <label for="img">img :</label>
      <input id="img" type="text" name="img" value="">



      <input class="button button-primary" type="submit" value="Ajouter le mangas">
    </fieldset>


    </fieldset>



  </form>

</div>
<?php } else {
  $http = new Http();
  $http->redirectTo('/');
} ?>
